### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-attribute#100]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] base_custom_attributes - To be removed
- [ ] customer_context_in_product_view
- [ ] partner_custom_attributes - To be removed
- [ ] pricelist_per_product - By @bmw95 - #189 
- [ ] product_attribute_multi_type - To be removed
- [x] product_brand - PR https://github.com/OCA/product-attribute/pull/128
- [ ] product_catalog_report
- [ ] product_custom_attributes - It should be removed as we have _product_custom_info_
- [ ] product_gift
- [ ] product_categ_attributes
- [x] product_custom_info - By @Yajo - #177
- [ ] product_customer_code
- [ ] product_electronic
- [ ] product_gtin - https://github.com/OCA/product-attribute/pull/132
- [x] product_dimension - By @leemannd - #159
- [ ] product_icecat
- [ ] product_index
- [ ] product_listprice_upgrade
- [ ] product_lot_foundry
- [x] product_manufacturer - By @komsas - #152
- [x] product_m2mcategories - Renamed to _product_multi_category_ by @SodexisTeam - #139 
- [ ] product_multi_company
- [x] product_multi_image - ~~By @SodexisTeam - #161~~ By @lasley - #199 
- [ ] product_multi_price
- [ ] product_pricelist_fixed_price
- [ ] product_prices_on_variant
- [ ] product_qt
- [ ] product_quick_stock_rule
- [ ] product_size
- [ ] product_search_reference
- [ ] product_sequence - PR https://github.com/OCA/product-attribute/pull/109
- [ ] product_series
- [ ] product_standard_price_tax_included
- [ ] product_supplierinfo_for_customer - By @aheficent - #287 
- [ ] product_supplierinfo_tree_price_info - To be removed as now there's not 2 levels of supplierinfo
- [ ] product_weight
- [ ] production_lot_custom_attributes

**Comment by SodexisTeam** [comment]
For info, we are porting product_m2mcategories module

**Comment by pedrobaeza** [comment]
Thanks for the great work migrating modules! What do you think of renaming the module to _product_multi_category_ to follow naming conventions and avoid plurals?

**Comment by atchuthan** [comment]
yes, we will rename it to product_multi_category.

Also, with regards to product_images module, it seems there is a pending migration at https://github.com/OCA/product-attribute/pull/57 in which it is renamed to product_multi_image.

Should I start the porting of product_multi_image module based on this PR?

**Comment by pedrobaeza** [comment]
@atchuthan, the correct module to be migrated to 9.0 is https://github.com/OCA/product-attribute/pull/135, that is the work that I started in the PR you have mentioned, but with a better base. The heavy load of the module has been moved to a generic module (_base_multi_image_) to be reusable, that is already merged in https://github.com/OCA/server-tools/tree/8.0/base_multi_image, so you'll need to also migrate that one, but you will see that you have to do very little, and it's by far more powerful than the previous versions.

**Comment by atchuthan** [comment]
okay, thanks for the info.

**Comment by SodexisTeam** [comment]
For info, we are migrating product_sequence.

There seems to be a PR associated with this module but no activity on it(since 10 Nov 2015).
So, we are going to create a new PR.

**Comment by leemannd** [comment]
Doing the product_dimension in https://github.com/OCA/product-attribute/pull/159

**Comment by flotho** [comment]
Hi,

You could add product dimension : https://github.com/OCA/product-attribute/pull/166

**Comment by flotho** [comment]
Please also consider this one https://github.com/OCA/product-attribute/pull/167 as WIP

**Comment by pedrobaeza** [comment]
Why 2 times product_dimension module?

**Comment by flotho** [comment]
Hi @pedrobaeza :
- My bad for product dimension, I'll fix it, is it also possible to merge the PR #159 which seems good
- I started to split the PR. Please consider this one as https://github.com/OCA/product-attribute/pull/170 as WIP.

**Comment by flotho** [comment]
@pedrobaeza , please consider https://github.com/OCA/product-attribute/pull/171 as migration of product_custom_attributes only ;-)

**Comment by flotho** [comment]
hi @pedrobaeza , please consider https://github.com/OCA/product-attribute/pull/172 as the migration of product_categ_only ;-)

**Comment by yajo** [comment]
Starting with product_custom_info

**Comment by flotho** [comment]
@Yajo , @pedrobaeza , just to be sure, it looks like product_custom_info is a replacement of product_custom_attributes, so, what about product_categ_attributes ? will it be a replacement too or any other recommandation ?

regards

**Comment by yajo** [comment]
Well, we actually do not use any of both, but given https://github.com/OCA/server-tools/pull/492 provides a great framework for custom information into any model, I think that should be the path. I guess I'm a little biased being the main developer of all the custom_info collection, but I think other modules that need migration should have 1 version (maybe v9) of deprecation (just depend on its *_custom_info counterpart and add a migration script that moves old to new).

However, as long as modules do not interfere with each other, there should be no problem on having all of them if you need them.

**Comment by pedrobaeza** [comment]
No, @Yajo, OCA's rules forbid to have 2 modules for the same purpose.

@flotho, _product_categ_attributes_ should be adapted to the new system, but it's very easy (a field _custom_info_template_id_ in product.category + onchange on product.product when changing the category for bringing the custom info template).

**Comment by flotho** [comment]
Hi @pedrobaeza thanks for your answer,
so if I understand well, using the cutom info modules instead of the custom attributes one + a migration for the product_categ_attributes will do the job. am I right?

**Comment by pedrobaeza** [comment]
Yes, you are

**Comment by yajo** [comment]
#177 was merged

**Comment by fanha99** [comment]
there are 2 line of product_custom_info in the list

**Comment by pedrobaeza** [comment]
Extra one removed.
