### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/product-attribute#1157]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] packaging_uom - By @gaelTorrecillas - #1399
- [x] pos_product_cost_security - By @chienandalu - #1661
- [x] product_abc_classification - By @rousseldenis - #1192
- [x] product_abc_classification_base - By @rousseldenis - #1192
- [x] product_abc_classification_sale_stock - By @rousseldenis - #1196
- [x] product_assortment - By @marielejeune - #1158
- [x] product_attachment_zipped_download - By @victoralmau - #1822
- [x] product_attribute_archive - By @Rferri44-S73 - #1301
- [x] product_attribute_value_menu - By @neuby001 - #1347
- [ ] product_categ_image - By @cubells - #1967
- [ ] product_category_active
- [ ] product_category_code
- [x] product_category_code_unique - By @manuelregidor - #1829
- [x] product_category_description - By @Tisho99 - #1842
- [ ] product_category_product_link
- [x] product_code_mandatory - By @ced-adhoc - #1693
- [x] product_code_unique - By @marielejeune - #1159
- [x] product_cost_security - By @bvanjeelharia - #1240
- [x] product_dimension - By @FrancoMaxime - #1168
- [x] product_expiry_configurable - By @rousseldenis - #1318
- [x] product_internal_reference_generator - By @sbiosca-s73 - #1485
- [ ] product_list_pricelist_price - By @MarinaAForgeFlow - #1572
- [x] product_logistics_uom - By @marielejeune - #1160
- [x] product_lot_sequence - By @AungKoKoLin1997 - #1296
- [x] product_main_supplierinfo - By @mmequignon - #1786
- [x] product_manufacturer - By @FrancoMaxime - #1166
- [x] product_multi_category - By @FrancoMaxime - #1167
- [x] product_multi_image - By @IJOL - #1707
- [x] product_net_weight - By @RabbitJon-S73 - #1281
- [x] product_origin - By @acsonefho - #1389
- [x] product_packaging_dimension - By @marielejeune - #1161
- [x] product_packaging_type - By @rousseldenis - #1215
- [ ] product_packaging_type_pallet - By @rousseldenis - #1216
- [ ] product_pricelist_by_contact - By @cubells - #2052
- [x] product_pricelist_direct_print - By @legalsylvain - #1365
- [x] product_pricelist_direct_print_company_group - By @stefan-tecnativa - #1382
- [x] product_pricelist_direct_print_website_sale - By @carolinafernandez-tecnativa - #1417
- [x] product_pricelist_revision - By @Yadier-Tecnativa - #1331
- [x] product_pricelist_simulation_margin - By @HugoCordobaLeal - #1354
- [x] product_pricelist_supplierinfo - By @andreagidaltig - #1373
- [ ] product_restricted_type
- [x] product_secondary_unit - By @remihb - #1325
- [x] product_sequence - By @marielejeune - #1162
- [ ] product_special_type - By @acsonefho - #1383
- [ ] product_standard_price_tax_included - By @legalsylvain - #1175
- [x] product_state - By @imarulbala - #1219
- [ ] product_state_history - By @michaelslade54 - #1396
- [ ] product_sticker - By @Shide - #1698
- [x] product_supplierinfo_archive - By @dsolanki-initos - #1361
- [x] product_supplierinfo_for_customer - By @FernandoRomera - #1230
- [x] product_supplierinfo_revision - By @stefan-tecnativa - #1387
- [x] product_supplierinfo_stock_picking_type - By @victoralmau - #1526
- [ ] product_template_tags -> partially obsolete because of `product.tag` in Odoo 16. See https://github.com/OCA/product-attribute/issues/1157#issuecomment-1334850916
- [x] product_total_weight_from_packaging - By @QuocDuong1306 - #1404
- [x] product_uom_measure_type - By @legalsylvain - #1189
- [x] product_uom_updatable - By @glitchov - #1286
- [ ] product_variant_attribute_name_manager
- [x] purchase_product_template_tags - By @LauraCForgeFlow - #1869
- [x] sale_product_template_tags
- [x] stock_product_template_tags - By @LauraCForgeFlow - #1870
- [ ] stock_production_lot_expiry - By @glitchov - #1214
- [ ] uom_extra_data - By @alexis-via - #1179

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow I will work on product_abc_classification following comments on https://github.com/OCA/product-attribute/pull/781 and try to  make converging.

I will take v10 version as base.

**Comment by MiquelRForgeFlow** [comment]
Isn't it better to get as base what is done in v13 and then refactor it in the way is commented in https://github.com/OCA/product-attribute/pull/781? I think this way will be easier to review.

**Comment by rousseldenis** [comment]
> Isn't it better to get as base what is done in v13 and then refactor it in the way is commented in #781? I think this way will be easier to review.

Mmmh, can try

**Comment by otmanelagy** [comment]
product_secondary_unit migred here #1193

**Comment by rousseldenis** [comment]
Migrating product_packaging_type to product_packaging_level following https://github.com/OCA/product-attribute/issues/1213

**Comment by imarulbala** [comment]
Migration to version 16.0

- product_state https://github.com/OCA/product-attribute/pull/1219

**Comment by rousseldenis** [comment]
Will migrate product_packaging_type_pallet => product_packaging_level_pallet

**Comment by mohammadazeem786** [comment]
Migration to version 16.0

-     sale_product_template_tags

**Comment by mohammadazeem786** [comment]
Migration to version 16.0

- product_template_tags

I we will not migrate the module because of the new functionality in Odoo 16: https://github.com/odoo/odoo/blob/16.0/addons/product/models/product_tag.py

These are the differences i can see between new functionality in Odoo 16 and OCA Module :
1. Unique constraints is only for name in odoo16 where OCA has unique constraints for company wise and name.
2. Product count is not present in Odoo16.
3. Product tags field is only in form view in odoo16 but OCA has tags in kanban,search,tree and form view.
4. Record rules are not present for multi company for tags but present in OCA.

**Comment by mohammadazeem786** [comment]
Migration to version 16.0

- sale_product_template_tags https://github.com/OCA/product-attribute/pull/1223

**Comment by matiasperalta1** [comment]
product_code_mandatory https://github.com/OCA/product-attribute/pull/1237

**Comment by rafaelbn** [comment]
@rousseldenis `product_category_product_link` I think is already in Odoo CE core. Both 15 and 16. At least I can go from categories to products. Just in case 😄

**Comment by Rferri44-S73** [comment]
product_attribute_archive https://github.com/OCA/product-attribute/pull/1301

**Comment by astirpe** [comment]
@rafaelbn indeed from a functional point of view, module `product_category_product_link` doesn't add anything new, since standard Odoo allows to go from categories to products. However `product_category_product_link` is just a technical module, adding a field `product_template_ids` inside the product category. That field is used by other modules, like `product_category_tax`, so I'm going to port `product_category_product_link` anyway.

**Comment by rousseldenis** [comment]
I will migrate product_expiry_configurable

**Comment by yaazkal** [comment]
Hi mods, I can see that @astirpe has actually migrated `product_category_product_link` here in this PR: https://github.com/OCA/product-attribute/pull/1302 if you can check and merge. Note this is need in order to validate this other PR from the `account-financial-tools` repo: https://github.com/OCA/account-financial-tools/pull/1618

**Comment by angelmoya** [comment]
Hi, can you update product_category_active, that was migrated on #1253

**Comment by hugo-cordoba** [comment]
I am working on 'product_pricelist_simulation' https://github.com/OCA/product-attribute/pull/1348

**Comment by hugo-cordoba** [comment]
I am working on 'product_pricelist_simulation_margin'. This module arises from the conversation held in https://github.com/OCA/margin-analysis/pull/177 PR: https://github.com/OCA/product-attribute/pull/1354

**Comment by flalexg** [comment]
Working on product_multi_price

**Comment by aliciagaarzo** [comment]
Im working on '**product_main_supplierinfo**'  https://github.com/OCA/product-attribute/pull/1353

**Comment by martiqubiq** [comment]
working on product_pricelist_by_contact

**Comment by hugho-ad** [comment]
Hello

product_pricelist_supplierinfo missing from the list @pedrobaeza @rousseldenis

**Comment by pedrobaeza** [comment]
Are you going to provide a PR with the migration? If so, we launch the command from the PR itself.

**Comment by bosd** [comment]
product_profile in #1366

**Comment by andreagidaltig** [comment]
> Hello
> 
> product_pricelist_supplierinfo missing from the list @pedrobaeza @rousseldenis

Working on **product_pricelist_supplierinfo**

**Comment by michaelslade54** [comment]
Hi, I am working on product_state_active and product_state_history.
Pull Requests:
product_state_active [#1392](https://github.com/OCA/product-attribute/pull/1392)
product_state_history [#1396](https://github.com/OCA/product-attribute/pull/1396)

**Comment by nuprodRomainF** [comment]
Hello we migrate product_category_product_link

https://github.com/OCA/product-attribute/pull/1420

**Comment by Kev-Roche** [comment]
Hello, 
Migration of product_tier_validation : https://github.com/OCA/product-attribute/pull/1539

**Comment by Kev-Roche** [comment]
Hello, I'm migrating : 
- https://github.com/OCA/product-attribute/pull/1574

**Comment by MarioLM-23** [comment]
Migration of product_code_mandatory module [#1575 ](https://github.com/OCA/product-attribute/pull/1575)

**Comment by alessandro-fiorino** [comment]
> Migration to version 16.0
> 
> * product_template_tags
> 
> I we will not migrate the module because of the new functionality in Odoo 16: https://github.com/odoo/odoo/blob/16.0/addons/product/models/product_tag.py
> 

It has been migrated after all https://github.com/OCA/product-attribute/tree/16.0/product_template_tags, shoud the status be updated and marked as done ?

**Comment by BhaveshHeliconia** [comment]
product_multi_price: [#1783](https://github.com/OCA/product-attribute/pull/1783)
