### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-attribute#184]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] ~~base_custom_attributes~~ : deprecated in 9.0 branch in favor of product_custom_info
- [ ] customer_context_in_product_view
- [ ] partner_custom_attributes 
- [ ] product_attribute_multi_type
- [x] product_brand - by @loxamir #191
- [ ] product_catalog_report
- [ ] product_categ_attributes
- [ ] product_custom_attributes
- [x] product_custom_info - By @fanha99 
- [X] ~~product_customer_code - By @pcatinean - #236~~ Deprecated for `product_supplierinfo_for_customer`
- [x] product_dimension - ~~By @gurneyalex #195~~ By @thomaspaulb - #491 
- [ ] product_electronic
- [ ] product_gift
- [ ] product_gtin
- [ ] product_icecat
- [ ] product_index
- [ ] product_listprice_upgrade
- [ ] product_lot_foundry
- [x] product_manufacturer - By @bistaray - #188 
- [x] product_multi_category - By @angelmoya - #242 
- [ ] product_multi_price
- [ ] product_pricelist_fixed_price
- [ ] product_prices_on_variant
- [ ] product_qt
- [ ] product_quick_stock_rule
- [ ] product_search_reference
- [x] product_sequence - by @sodexisteam #194 
- [ ] product_series
- [ ] product_size
- [X] ~~product_supplierinfo_tree_price_info~~ Not needed anymore as the structure has changed.
- [ ] product_supplierinfo_for_customer - @aheficent - #292
- [ ] product_supplierinfo_for_customer_sale - @aheficent https://github.com/OCA/product-attribute/pull/280#issuecomment-316748306
- [x] product_uom - By @lasley - #213 
- [ ] product_weight
- [ ] production_lot_custom_attributes

**Comment by yajo** [comment]
@pedrobaeza I think you got confused:

> [x]  product_custom_info - By @Yajo - #177

#177 is for v9

**Comment by pedrobaeza** [comment]
Right, totally. Fixed.

**Comment by ysantiago** [comment]
@pedrobaeza What about module product_supplierinfo_for_customer?

**Comment by pedrobaeza** [comment]
The module was not in the repository before. When decided what to do, it can be added here.

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza product_supplierinfo_for_customer_sale depends on product_supplierinfo_for_customer in v8. Thus, I'll wait until we decide.

**Comment by ysantiago** [comment]
@pedrobaeza @aheficent that is my point about product_supplierinfo_for_customer.

**Comment by AaronHForgeFlow** [comment]
As discussed here: https://github.com/OCA/product-attribute/pull/236 `product_customer_code` will be deprecated in favour of `product_supplierinfo_for_customer` If nobody else is working on product_supplierinfo_for_customer I will take it.

**Comment by lasley** [comment]
@aheficent added & tagged you to it

**Comment by AaronHForgeFlow** [comment]
product_supplierinfo_for_customer - @aheficent #292

**Comment by safecoms** [comment]
Hi guys,
we migrated to version 10 the module to print in PDF the price list.
how do we make it available for you in your branch for v10?
Sorry about the question but we are new to this part? I just want to make sure we do it right.

Cheers

**Comment by pedrobaeza** [comment]
See https://odoo-community.org/page/code and https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by gurneyalex** [comment]
I updated the list : base_custom_attributes was dropped in v9, in favor of product_custom_info

**Comment by JordiADARIA** [comment]
Hi! why not migrate product_attribute_priority to v10? i think it'll be a usefull tool for everybody

**Comment by pedrobaeza** [comment]
Because nobody has done it yet. You can do it or finance someone to do it if you think it's useful.

**Comment by fanha99** [comment]
going to migrate product_custom_info

**Comment by pedrobaeza** [comment]
:+1:

**Comment by zeroheure** [comment]
product_attribute_priority and product_supplierinfo_revision are missing on the "Modules to migrate" list, on the table in Readme for 10 version and in the git tree for 10.

**Comment by pedrobaeza** [comment]
@zeroheure they were added to the branch after the 11.0 branch creation. No problem in adding them later when there are PRs.

**Comment by zeroheure** [comment]
@pedrobaeza thanks, I will try to port them with my little knowledge of Python :)

**Comment by rousseldenis** [comment]
Will port https://github.com/OCA/sale-workflow/tree/10.0/product_special_type here.
