### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-attribute#293]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] customer_pricing_in_product_view - By @dsolanki-initos - #745
- [ ] partner_custom_attributes
- [ ] product_attribute_multi_type - By @dsolanki-initos - #741 
- [x] product_brand - ~~By @jprobineau - #301~~ By @Daniel-CA - #340 
- [ ] product_catalog_report
- [ ] product_categ_attributes
- [ ] product_custom_info
- [ ] product_customer_code
- [ ] product_default_image - By @dsolanki-initos - #749 
- [x] product_dimension - By @BT-kaberer - #337 
- [ ] product_electronic
- [ ] product_gift
- [ ] product_gtin
- [ ] product_icecat
- [ ] product_index
- [ ] product_listprice_upgrade
- [ ] product_lot_foundry
- [x] product_manufacturer - By @lreficent - #329 
- [x] product_multi_category - By @damcar - #295 
- [ ] product_multi_image - By @qtheuret - #358  
- [ ] product_multi_price
- [x] product_pricelist_direct_print - By @chienandalu - #370 
- [x] ~~product_pricelist_fixed_price~~ - Not needed anymore as feature is now in core
- [ ] product_pricelist_tier - By @dsolanki-initos - #746 
- [ ] product_prices_on_variant
- [ ] product_qt
- [ ] product_quick_stock_rule
- [ ] product_search_reference
- [x] product_sequence - By @lreficent - #341 
- [ ] product_series
- [ ] product_service_duration
- [ ] product_size
- [x] product_state - By @asaunier - #345 
- [x] product_supplierinfo_for_customer - By @mreficent - #378 
- [x] product_supplierinfo_for_customer_sale - ~~By @moylop260 - #395~~ Moved to OCA/sale-workflow#681
- [x] product_supplierinfo_revision - By @cubells - #348
- [x] product_template_tags - By @foutoucour - #362
- [x] product_uom > product_uom_extra_data - ~~By @hprasetyou - #351 By @mreficent - #423~~ By @mreficent - OCA/community-data-files#54
- [x] product_weight - By @jhumfer - #375

**Comment by jprobineau** [comment]
@pedrobaeza :product_brand

**Comment by LoisRForgeFlow** [comment]
product_manufacturer https://github.com/OCA/product-attribute/pull/329

**Comment by Daniel-CA** [comment]
I claim product_brand, looks like that @jprobineau  is not working with it anymore. #340

**Comment by LoisRForgeFlow** [comment]
product_sequence https://github.com/OCA/product-attribute/pull/341

**Comment by asaunier** [comment]
Hi @pedrobaeza 
PR #345 proposes to migrate product_state => **merged**

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza 

We're going to migrate product_customer_code to V11. But I don't know if product_customer_code has been deprecated in favor of product_customer_code_sale (sale-workflow).

Which one should we work in?

Thanks!

**Comment by pedrobaeza** [comment]
@HaraldPanten yes, that one has been deprecated in favor of product_supplierinfo_for_customer* family of modules, so you should migrate that one instead. Version 10 of the module is already merged in https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer

**Comment by HaraldPanten** [comment]
Thank you @pedrobaeza 

I'm going to check https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer functionalities

**Comment by HaraldPanten** [comment]
Good morning @pedrobaeza ,

I’ve tested this module https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer but I couldn’t put into practice the casuistry that I was trying to do.

I need to show the product name/code for different partners in the sale order.

In V8, there was an extended functionality for product_supplierinfo_for_customer module that met this need, it was this one → https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_for_customer_sale

In addition, there’s an important known issue detected in https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer that hasn’t been solved yet:

1- The minimum quantity will neither apply on sale orders.

My questions are:

What’s the point on allowing the user to select a different product name, code and minimal quantity if this information is not going to be shown in the sales order?

We should merge the functionalities from https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer and https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_for_customer_sale in a single module. Shouldn’t we?

Let me know which is the best way to proceed and I’m going to take care of the migration to V11 with these extended functionalities → product_supplierinfo_for_customer + product_supplierinfo_for_customer_sale in a single module.

Thx!

**Comment by pedrobaeza** [comment]
That module is only the base. You need the module product_supplierinfo_for_customer_sale for what you are saying. See a PR that it's in progress.

**Comment by ProcessControl-JHF** [comment]
**product_weight** #375

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check product_state - By @asaunier - #345 because it is already merged

product_supplierinfo_for_customer_sale - By @moylop260 - #395 is closed and moved to OCA/sale-workflow. It is already merged OCA/sale-workflow#681

Please, add to the list product_supplierinfo_revision - By @cubells - #348 that is already migrated and merged

**Comment by emagdalenaC2i** [comment]
Please, add to the list product_template_tags - By @foutoucour - #362 

The PR number in product_multi_image - By @FFernandez-PlanetaTIC - #359 is wrong, it should be #358

There is a PR for the migration of product_uom - By @hprasetyou - #351

**Comment by emagdalenaC2i** [comment]
Please, check product_uom - By @hprasetyou - #351 By @mreficent - #423 that was renamed as product_uom_extra_data and moved to OCA/community-data-files https://github.com/OCA/community-data-files/pull/54 that is already merged

**Comment by patel1008b** [comment]
Anyone had done **product_lot_foundry** migration? It is required in the foundry industry. Please let me know if someone had a module in v11 or v12.

**Comment by pedrobaeza** [comment]
Not at least notified here.

**Comment by FFernandez-PlanetaTIC** [comment]
`product_multi_image` in #358 by @qtheuret, not me

**Comment by rafaelbn** [comment]
As commented in the PR, product_multi_image is not needed any more, Odoo has it by default from v11

![2019-09-05_2-20-28](https://user-images.githubusercontent.com/8736623/64302571-44e4f880-cf84-11e9-8458-161d5edcb6c7.png)

**Comment by FFernandez-PlanetaTIC** [comment]
See https://github.com/OCA/product-attribute/pull/358#issuecomment-528880199

**Comment by fshah-initos** [comment]
Hello all,

I've migrated module product_custom_info to v11. Here is the PR https://github.com/OCA/product-attribute/pull/740
Here is the PR of base_custom_module https://github.com/OCA/server-tools/pull/1952. (This PR is added as it is dependent on product_custom_info module).

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module  product_attribute_multi_type and here is the PR #741

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated  the module  customer_pricing_in_product_view and here is the PR #745

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module product_pricelist_tier to v11 and here is the PR #746

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module product_service_duration and here is the PR #747

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module product_default_image and here is the PR #749
